import { describe, expect, it } from 'vitest';
import type { ElectoralInterpretationContext } from './electoral-interpretation-context';
import { interpretElectoralContext } from './electoral-interpretation';
import { buildElectoralBriefing } from './electoral-briefing';
import { validateElectoralBriefing } from './electoral-briefing-guards';

function source(): ElectoralInterpretationContext {
  const provenance = { territoryId: 't1', years: [2016, 2020, 2024], metricKeys: ['election'], datasets: ['TSE'], evidenceHashes: ['h1'] };
  const facts = [2016, 2020, 2024].map((year) => ({ assertionClass: 'FACT' as const, year, electorate: 1000, turnout: 770, turnoutRate: year === 2024 ? 77 : 78, abstention: 230, abstentionRate: year === 2024 ? 23 : 22, validVotes: 750, winner: year === 2016 ? 'ANA LIMA' : 'MARIA SILVA', winnerParty: year === 2016 ? 'PSDB' : 'PT', runnerUp: 'JOAO SOUZA', runnerUpParty: 'PL', marginVotes: year === 2024 ? 300 : 200, marginPercentagePoints: year === 2024 ? 30 : 20, decisiveRound: year === 2024 ? 1 : 2, officialStatus: 'ELEITO', provenance }));
  const make = (signalType: ElectoralInterpretationContext['signals'][number]['signalType'], metric: string, value: number | string, comparison: number | string, delta: number | null, fromYear: number | undefined = 2020) => ({ signalType, origin: 'COMPARATIVE_SIGNAL' as const, metric, period: { fromYear, toYear: 2024 }, value, comparison, delta, provenance });
  const keyChanges = [make('PARTICIPATION_DECREASED', 'turnoutRate', 77, 78, -1), make('ABSTENTION_INCREASED', 'abstentionRate', 23, 22, 1), make('MARGIN_EXPANDED', 'marginPercentagePoints', 30, 20, 10), make('WINNER_MAINTAINED', 'winner', 'MARIA SILVA', 'MARIA SILVA', null), make('WINNING_PARTY_MAINTAINED', 'winnerParty', 'PT', 'PT', null), make('DECISION_MOVED_TO_FIRST_ROUND', 'decisiveRound', 1, 2, null)];
  const benchmarkSignals = [make('BELOW_SAMPLE_PARTICIPATION', 'turnoutRate', 77, 79, -2, undefined), make('ABOVE_SAMPLE_ABSTENTION', 'abstentionRate', 23, 21, 2, undefined), make('ABOVE_SAMPLE_MARGIN', 'marginPercentagePoints', 30, 25, 5, undefined)];
  return { schemaVersion: 'electoral-context-v1', territory: { id: 't1', codigoIbge: '3118601', municipio: 'Contagem', uf: 'MG', comparisonUniverse: 'homologated-six-municipality-sample', comparisonUniverseLabel: 'amostra homologada de seis municípios' }, scope: { from: 2016, to: 2024, years: [2016, 2020, 2024], sourceSignalCount: 9 }, elections: facts, currentSnapshot: facts[2], historicalEvolution: facts.slice(0, 2), participation: facts.map(({ year, turnoutRate, abstentionRate }) => ({ year, turnoutRate, abstentionRate })), competition: facts.map(({ year, marginVotes, marginPercentagePoints }) => ({ year, marginVotes, marginPercentagePoints })), winnerHistory: facts.map(({ year, winner }) => ({ year, winner })), partyHistory: facts.map(({ year, winnerParty: party }) => ({ year, party })), decisionRoundHistory: facts.map(({ year, decisiveRound }) => ({ year, decisiveRound })), benchmark: benchmarkSignals.map((signal) => ({ assertionClass: 'FACT', metric: signal.metric, year: 2024, comparisonUniverse: 'homologated-six-municipality-sample', comparisonUniverseLabel: 'amostra homologada de seis municípios', sampleAverage: Number(signal.comparison), municipalityValue: Number(signal.value), deltaToSample: signal.delta!, signalType: signal.signalType, provenance })), signals: [...keyChanges, ...benchmarkSignals], keyChanges, provenance, sourcesUsed: { datasets: ['TSE'], evidenceHashes: ['h1'] }, limitations: ['benchmark limitado à amostra homologada de seis municípios', 'causalidade não estabelecida'], missingData: [], interpretationGuardrails: { allowed: ['descrever'], prohibited: ['prever'] }, assertions: { facts: [], interpretations: [], recommendations: [] } };
}

const valid = () => { const context = source(); const interpretation = interpretElectoralContext(context); return { context, interpretation, briefing: buildElectoralBriefing(context, interpretation) }; };

describe('ElectoralBriefing', () => {
  it('constrói contrato válido, compacto e determinístico', () => { const a = valid(); const b = valid(); expect(a.briefing.schemaVersion).toBe('electoral-briefing-v1'); expect(a.briefing).toEqual(b.briefing); expect(a.briefing.interpretations).toHaveLength(a.interpretation.interpretations.length); });
  it('preserva cobertura, histórico, limitações e benchmark', () => { const { briefing } = valid(); expect(briefing.coverage.availableYears).toEqual([2016, 2020, 2024]); expect(briefing.coverage.missingYears).toEqual([]); expect(briefing.historicalEvolution).toHaveLength(3); expect(briefing.limitations).toContain('causalidade não estabelecida'); expect(briefing.benchmark.every((item) => item.comparisonUniverseLabel === 'amostra homologada de seis municípios')).toBe(true); });
  it('preserva interpretações, tensões, continuidades, mudanças e confiança', () => { const { briefing } = valid(); expect(briefing.tensions).toHaveLength(1); expect(briefing.continuityAndChange.continuities.length).toBeGreaterThan(0); expect(briefing.continuityAndChange.changes.length).toBeGreaterThan(0); expect(briefing.confidence.classesPresent).toContain('LIMITED_CONTEXT'); });
  it('mantém referências e classes FACT/SIGNAL/INTERPRETATION', () => { const { context, interpretation, briefing } = valid(); expect(validateElectoralBriefing(context, interpretation, briefing).valid).toBe(true); expect(briefing.guardrails.assertionClasses).toEqual(['FACT', 'SIGNAL', 'INTERPRETATION']); expect(briefing.evidence.hashes).toEqual(['h1']); });
  it('representa contexto insuficiente sem preencher lacunas', () => { const context = source(); context.elections = []; context.currentSnapshot = null; context.historicalEvolution = []; const interpretation = interpretElectoralContext(context); const briefing = buildElectoralBriefing(context, interpretation); expect(briefing.coverage.missingYears).toEqual([2016, 2020, 2024]); expect(briefing.executiveSummary.keyPoints).toEqual([]); });
  it.each([
    ['referência quebrada', (b: ReturnType<typeof valid>['briefing']) => { b.executiveSummary.references.push('missing'); }, 'REFERENCE'],
    ['interpretação alterada/número inventado', (b) => { b.interpretations[0].statement = 'A participação foi 999.'; }, 'NUMBER'],
    ['entidade inventada', (b) => { b.interpretations[0].statement = 'FERNANDO COSTA venceu.'; }, 'ENTITY'],
    ['recomendação', (b) => { b.guardrails.recommendations = ['o candidato deve atacar'] as never; }, 'RECOMMENDATION'],
    ['previsão', (b) => { b.interpretations[0].statement = 'MARIA SILVA vai vencer.'; }, 'PREDICTION'],
    ['causalidade', (b) => { b.interpretations[0].statement = 'A queda ocorreu porque houve rejeição.'; }, 'CAUSALITY'],
    ['benchmark RMBH', (b) => { b.benchmark[0].comparisonUniverseLabel = 'média da RMBH' as never; }, 'BENCHMARK'],
    ['limitação removida', (b) => { b.limitations = []; }, 'LIMITATION'],
    ['evidência inexistente', (b) => { b.interpretations[0].evidenceRefs = ['fake']; }, 'REFERENCE'],
    ['partido inexistente', (b) => { b.interpretations[0].statement = 'PARTIDO NOVO FALSO venceu.'; }, 'ENTITY'],
    ['opinião do eleitor', (b) => { b.executiveSummary.headline = 'O eleitor prefere mudança.'; }, 'VOTER_OPINION'],
  ])('rejeita fixture adversarial: %s', (_name, mutate, expected) => { const fixture = valid(); mutate(fixture.briefing); expect(validateElectoralBriefing(fixture.context, fixture.interpretation, fixture.briefing).errors.map((item) => item.guard)).toContain(expected); });
});
